# Generated by Django 4.1.7 on 2023-03-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('ZaloPay', 'ZaloPay'), ('Visa', 'Visa'), ('MoMo', 'MoMo'), ('ATM', 'ATM'), ('Mastercard', 'Mastercard'), ('Wallet', 'Wallet')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('On The Way', 'On The Way'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Packed', 'Packed'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='name',
            field=models.CharField(choices=[('ZaloPay', 'ZaloPay'), ('Visa', 'Visa'), ('MoMo', 'MoMo'), ('ATM', 'ATM'), ('Mastercard', 'Mastercard'), ('Wallet', 'Wallet')], default='Wallet', max_length=50),
        ),
    ]
