# Generated by Django 4.1.7 on 2023-03-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_alter_payment_payment_option_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('Wallet', 'Wallet'), ('ZaloPay', 'ZaloPay'), ('Mastercard', 'Mastercard'), ('Visa', 'Visa'), ('ATM', 'ATM'), ('MoMo', 'MoMo')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('On The Way', 'On The Way'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='name',
            field=models.CharField(choices=[('Wallet', 'Wallet'), ('ZaloPay', 'ZaloPay'), ('Mastercard', 'Mastercard'), ('Visa', 'Visa'), ('ATM', 'ATM'), ('MoMo', 'MoMo')], default='Wallet', max_length=50),
        ),
    ]
