# Generated by Django 4.1.7 on 2023-03-22 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_alter_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ratting',
        ),
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='Shop.comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('Card', 'Card'), ('MoMo', 'MoMo'), ('Wallet', 'Wallet')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('On The Way', 'On The Way'), ('Pending', 'Pending'), ('Packed', 'Packed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='name',
            field=models.CharField(choices=[('Card', 'Card'), ('MoMo', 'MoMo'), ('Wallet', 'Wallet')], max_length=50),
        ),
    ]
