# Generated by Django 4.1.7 on 2023-03-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_alter_payment_payment_option_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('MoMo', 'MoMo'), ('Wallet', 'Wallet'), ('Card', 'Card')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Packed', 'Packed'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('On The Way', 'On The Way')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='name',
            field=models.CharField(choices=[('MoMo', 'MoMo'), ('Wallet', 'Wallet'), ('Card', 'Card')], max_length=50),
        ),
    ]
