# Generated by Django 4.1.7 on 2023-03-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_alter_payment_payment_option_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('Visa', 'Visa'), ('ZaloPay', 'ZaloPay'), ('Mastercard', 'Mastercard'), ('Wallet', 'Wallet'), ('MoMo', 'MoMo'), ('ATM', 'ATM')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Packed', 'Packed'), ('Delivered', 'Delivered'), ('On The Way', 'On The Way'), ('Accepted', 'Accepted')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='name',
            field=models.CharField(choices=[('Visa', 'Visa'), ('ZaloPay', 'ZaloPay'), ('Mastercard', 'Mastercard'), ('Wallet', 'Wallet'), ('MoMo', 'MoMo'), ('ATM', 'ATM')], default='Wallet', max_length=50),
        ),
    ]
