# Generated by Django 4.1.7 on 2023-03-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_alter_payment_payment_option_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('ZaloPay', 'ZaloPay'), ('ATM', 'ATM'), ('MoMo', 'MoMo'), ('Mastercard', 'Mastercard'), ('Wallet', 'Wallet'), ('Visa', 'Visa')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('On The Way', 'On The Way'), ('Packed', 'Packed'), ('Pending', 'Pending'), ('Accepted', 'Accepted')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='name',
            field=models.CharField(choices=[('ZaloPay', 'ZaloPay'), ('ATM', 'ATM'), ('MoMo', 'MoMo'), ('Mastercard', 'Mastercard'), ('Wallet', 'Wallet'), ('Visa', 'Visa')], default='Wallet', max_length=50),
        ),
    ]
