# Generated by Django 4.1.7 on 2023-03-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_alter_payment_payment_option_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('ATM', 'ATM'), ('Wallet', 'Wallet'), ('ZaloPay', 'ZaloPay'), ('Visa', 'Visa'), ('MoMo', 'MoMo'), ('Mastercard', 'Mastercard')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Packed', 'Packed'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='name',
            field=models.CharField(choices=[('ATM', 'ATM'), ('Wallet', 'Wallet'), ('ZaloPay', 'ZaloPay'), ('Visa', 'Visa'), ('MoMo', 'MoMo'), ('Mastercard', 'Mastercard')], max_length=50),
        ),
    ]
