# Generated by Django 4.1.7 on 2023-03-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_alter_payment_payment_option_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Pending', 'Pending'), ('On The Way', 'On The Way'), ('Accepted', 'Accepted')], default='Pending', max_length=50),
        ),
    ]
