# Generated by Django 4.1.5 on 2023-03-02 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shop', '0037_alter_orderplaced_status_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('On The Way', 'On The Way')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('Wallet', 'Wallet'), ('Card', 'Card')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='name',
            field=models.CharField(choices=[('Wallet', 'Wallet'), ('Card', 'Card')], max_length=50),
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Shop.comment')),
            ],
        ),
    ]
