# Generated by Django 4.1.5 on 2023-03-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0039_comment_parent_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Way', 'On The Way'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Packed', 'Packed'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
    ]
